#!/usr/bin/env bash
# Install watermarks-remover as a *global* git pre-commit hook: every repo
# on this machine gets scanned (and optionally cleaned) at commit time,
# without adding a .pre-commit-config.yaml to each one.
#
# Mechanism: sets `git config --global core.hooksPath` to a managed
# directory and drops our pre-commit script there. If that directory (or an
# existing core.hooksPath) already has a pre-commit script, it is preserved
# as `pre-commit.pre-watermarks-remover` and chained to (see the hook file
# itself for details) — this does not clobber other global-hook tooling.
#
# Usage:
#   ./service/scripts/install_global_hooks.sh                 # detect mode (default)
#   WATERMARKS_REMOVER_MODE=clean ./service/scripts/install_global_hooks.sh
#   WATERMARKS_REMOVER_GLOBAL_HOOKS_DIR=~/my/hooks ./service/scripts/install_global_hooks.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOOK_SRC="$REPO_ROOT/service/scripts/git_hooks/pre-commit"

if [ ! -f "$HOOK_SRC" ]; then
  echo "install_global_hooks.sh: missing $HOOK_SRC (run from a watermarks-remover checkout)" >&2
  exit 1
fi

EXISTING_HOOKS_PATH="$(git config --global --get core.hooksPath 2>/dev/null || true)"
HOOKS_DIR="${WATERMARKS_REMOVER_GLOBAL_HOOKS_DIR:-${EXISTING_HOOKS_PATH:-$HOME/.config/git/hooks}}"
# Expand a leading ~ if it slipped in via env/config.
HOOKS_DIR="${HOOKS_DIR/#\~/$HOME}"

mkdir -p "$HOOKS_DIR"
DEST="$HOOKS_DIR/pre-commit"
CHAINED="$HOOKS_DIR/pre-commit.pre-watermarks-remover"

if [ -f "$DEST" ] && ! grep -q "watermarks-remover-global-hook" "$DEST"; then
  if [ -f "$CHAINED" ]; then
    echo "install_global_hooks.sh: $DEST is a foreign hook but $CHAINED already exists — refusing to overwrite it. Resolve manually." >&2
    exit 1
  fi
  echo "install_global_hooks.sh: preserving existing hook -> $CHAINED"
  mv "$DEST" "$CHAINED"
  chmod +x "$CHAINED"
fi

cp "$HOOK_SRC" "$DEST"
chmod +x "$DEST"

git config --global core.hooksPath "$HOOKS_DIR"

CONFIG_DIR="$HOME/.config/watermarks-remover"
CONFIG_FILE="$CONFIG_DIR/global-hooks.conf"
mkdir -p "$CONFIG_DIR"
{
  echo "# generated by install_global_hooks.sh — do not edit by hand, re-run the installer instead"
  echo "WATERMARKS_REMOVER_HOME=\"$REPO_ROOT\""
} >"$CONFIG_FILE"

echo "watermarks-remover: global pre-commit hook installed."
echo "  hooksPath: $HOOKS_DIR"
echo "  config:    $CONFIG_FILE (WATERMARKS_REMOVER_HOME=$REPO_ROOT)"
echo "  mode:      check (default) — set 'git config watermarks-remover.mode clean' per repo, or"
echo "             'git config --global watermarks-remover.mode clean' for every repo, to auto-clean instead."
echo "  opt out:   'git config watermarks-remover.enabled false' in any repo you want to skip."
echo "  uninstall: ./service/scripts/uninstall_global_hooks.sh"
